### ISSUE TITLE
Put all extended info (flow diagram, ...) into Wiki

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/TMSEG#4]

**Comment by Startouf** [comment]
Uploaded to wiki. The Flow chart file is a somewhat light .pdf, I believe t's ok to version it. Otherwise we'll add it to git-lfs. (The source file is a GDrive/draw.io of 2KB, a shame it turns into a 164 KB pdf file...)

**Comment by BernhoferM** [comment]
Hi,
and sorry for the inconveniences, but I forgot to update the rostlab wiki after releasing TMSEG v2.1.0 (however, it is up-to-date now).
In the new version the long helix size cutoff is now 34 residues (instead of 36) and the performance values have changed slightly. You can just compare the old and new revisions to see the changes or copy the new text altogether.

**Comment by juanmirocks** [comment]
@BernhoferM related to this, do you have unit tests implemented or any kind of managed benchmark that _proves_ that your new changes improve performance?

**Comment by BernhoferM** [comment]
I do have a dataset of transmembrane and soluble proteins, split into four equal parts. Split 1-3 are used for three-fold cross-training and cross-validation to optimize TMSEG's parameters. Split 4 is used at the end for the final (reported) performance.
Though v2.1.0's reported performance is only slithly different from v2.0.0, it is more robust when using different databases for the PSSM profiles.

I do have some java code for the training/optimization/validation, but not everything of it is completely automated. I can also give you the dataset and PSSM profiles if you want them, though I do not think they should be in the repository (over a thousand protein files and multiple PSSM profiles per protein).

**Comment by juanmirocks** [comment]
Those files and the knowledge of what you just described of how you test the performance, must certainly be somehow linked and documented in this repository.

If the dataset occupies a few megabytes, I would just include them in the repository. If they are too big, I would put them in the github large files. And then in the README put a link to them so that any user can use them to test the performance.

And finally, ideally indeed the tests should be automated. If you already have some code, even minimal, please commit it :-)

**Comment by juanmirocks** [comment]
I guess I can close this issue already.
- I moved MIchael's description on the benchmarking to the README so far
- I created issues #5 and #6 for the last points of the discussion
