### ISSUE TITLE
Commit or link training/test dataset

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/TMSEG#6]
See discussion in: https://github.com/Rostlab/TMSEG/issues/4#issuecomment-162535152

**Comment by BernhoferM** [comment]
The dataset consists of ~6,500 files, ~165MB total. Packed into a single .zip file it's ~35MB (due to beeing text files).
Which one would you prefer? The .zip file with git-lfs, or the single files within git/git-lfs?

**Comment by juanmirocks** [comment]
What do you think is best and finally simplest for users?

I would say .zip on git-lfs suffices

**Comment by BernhoferM** [comment]
Okay, I have commited the datasets and training/validation scripts as a single compressed file.
I decided to combine them as you would need a dataset to perform the training/validation any way.

**Comment by juanmirocks** [comment]
Thanks Michael. I will look into this.

**Comment by juanmirocks** [comment]
:+1:
