### ISSUE TITLE
Need build system in place

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/TMSEG#7]
The .jar is committed and works just fine. However, as we discussed before, in fact this binary file and all other ones (like debian packages) should not be committed directly to the repository. They should only be placed in the repo _downloads_ list. Also, since it's a java program, I don't understand why we have the makefiles.

What we need is rather the `maven` (.pom) (or ant? gradle?) file.
- [x] Have build system place and make the .jar be generated by it

**Comment by juanmirocks** [comment]
@BernhoferM do you have already a pom file?

**Comment by BernhoferM** [comment]
I have no .pom file, sorry (I've actually never used maven). I have always used my IDE (Eclipse) to build my .jar (or .class) files.
Unfortunately, I'm quite busy this/next week and I don't think I'll have time to work on TMSEG.

Regarding the makefiles:
They are only used for the debian package (e.g. ./src/Makefile.am to determine the destination folders for the different files). TMSEG was my first/only debian package, so I had to look for examples on how to build one. If there is a better/cleaner way, I'm open for change.

**Comment by juanmirocks** [comment]
Thanks a lot @BernhoferM Let's do things step by step :-)

Here is a quite good example of a .pom file: https://github.com/tagtog/JBioC/blob/master/pom.xml

Therefore, we just need to know all the dependencies. 

@Startouf could you guys finalize the .pom file ?

**Comment by juanmirocks** [comment]
@Startouf @mkeribin FYI I could perfectly run the tool with your provided instructions. Good job!

**Comment by Startouf** [comment]
@jmcejuela I will write the pom file it will be pretty easy. I will also try to see if I can somehow automate the performance tests of #5 with additional build plans in this pom file.

**Comment by juanmirocks** [comment]
:+1: nice

**Comment by juanmirocks** [comment]
@Startouf hey could you take a look at this?

**Comment by Startouf** [comment]
@jmcejuela The pom file for automatic building of the program has been committed 2 weeks ago (3d5e5b5). Concerning the automation of tests, I thought I would have had time, but I had too many other projects and exams to prepare and kinda forgot about it. Do you want it that badly for next Thursday ?

**Comment by juanmirocks** [comment]
I missed to see it. I just run it and works :+1: 

As for #5 that task is really optional. So feel free either way.
