### ISSUE TITLE
git lfs - out of quota error

### ISSUE THREAD

**Issue by slukowski** [Rostlab/TMSEG#8]
Hi

I'm interested in running TMSEG but I'm not having any luck with cloning it. I am receiving an error saying the repo is over its quota for git lfs.

```
Git LFS: (0 of 6 files) 0 B / 292.97 MB
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
```

I'm not sure how actively this repo is maintained now, but is this something you could please assist me with? Could you suggest a workaround if git lfs is not the way forward?

Thanks!
Sam

**Comment by BernhoferM** [comment]
Hi,

Please send me an email to bernhoferm@rostlab.org and I'll provide you an alternative link for the model files.

Regards
Michael Bernhofer

**Comment by slukowski** [comment]
Thank you very much Michael. I will email you directly.

Thanks again
Sam
