### ISSUE TITLE
Unable to run TMSEG locally

### ISSUE THREAD

**Issue by ktsirigos** [Rostlab/TMSEG#9]
Hi!

I have successfully installed TMSEG's current version, using the README instructions. However, when I try to run, I get the following error:

```
<predictors.HelixIndexer> Error: Failed to load model file(s) ./TMSEG-develop/src/models/hIndexer.[model|model.gz]
<predictors.HelixPredictor> Error: Failed to load model file(s) ./TMSEG-develop/src/models/hPredictor.[model|model.gz]
<predictors.TopologyPredictor> Error: Failed to load model file(s) ./TMSEG-develop/src/models/tPredictor.[model|model.gz]
```

Basically, it does not load the models files, although I can see them being present. Even when I install TMSEG in the path, it still does not load the models, from e.g.  `/usr/local/share/tmseg/models/`

What can be the issue?

**Comment by BernhoferM** [comment]
Hi.

One reason I could think of would be that the Git LFS checkout did not work (might be over the data limit). Do those model files contain any data or are they just empty files?

If this is the case, you can download the model files from our FTP server: ftp://rostlab.org/tmseg/

Regards
Michael Bernhofer

**Comment by ktsirigos** [comment]
Thanks Michael for a prompt response. Actually you are right, I thought they were  OK, because they were not empty, but they do not contain models. E.g., I see this:

```
version https://git-lfs.github.com/spec/v1
oid sha256:fa1dc847b42f4df2ba912772cb15dbe842b27c0abf1adb49671505b1c8a7a08c
size 83919
```
I tried with the FTP but I cannot reach it, is it possible to send me the files somehow, here or on my email?

**Comment by BernhoferM** [comment]
Unfortunately, the models are a bit big for email (~30MB). We could try and see if it'll get through, though.

The direct link to the file on the FTP is: ftp://rostlab.org/tmseg/models/models.zip
It should work with something like `wget` or `curl` (I've tried it just now) or just open the parent-path inside the file explorer (if you're on Windows). Don't try the link in Firefox, for example, as it does no longer support FTP protocol as far as I know.

If those methods fail, send me an email to bernhoferm@rostlab.org and I'll try to send you the file via that email address.

**Comment by ktsirigos** [comment]
Sent you an email Michael, thanks!

**Comment by ktsirigos** [comment]
All good Michael, managed to download them after all! It works fine now, many thanks for the help :)
